import type { Figure } from './types';

/**
 * Catalogo completo delle figure del testo, capitolo per capitolo.
 *
 * È la trascrizione dell'indice delle tavole: serve per sapere **che cosa
 * saper disegnare** e per ritrovare la figura sul libro. Le tavole stesse non
 * sono riprodotte — sono protette da copyright — ma dove esiste uno schema
 * **ridisegnato in forma originale** (`diagramId`, in `diagrams.ts`) la scheda
 * lo mostra e permette di esercitarsi a completarlo.
 *
 * Le figure che si prestano al «completa l'immagine» d'esame sono gli schemi a
 * blocchi; diagrammi temporali, tabelle e circuiti a transistori restano in
 * elenco perché fanno parte del programma, ma non diventano esercizi.
 */
export const figures: Figure[] = [
  // ─────────────── cap. 1 · Struttura di base ───────────────
  {
    id: 'fig-1-1',
    diagramId: 'unita-funzionali',
    code: 'fig. 1.1',
    desc: 'Unità funzionali di un calcolatore',
    area: 'cap. 1 · Struttura di base',
    topic: 'cpu',
  },
  {
    id: 'fig-1-2',
    diagramId: 'processore-memoria',
    code: 'cap. 1',
    desc: 'Processore e memoria principale: PC, IR, registri generali, ALU, controllo',
    area: 'cap. 1 · Struttura di base',
    topic: 'cpu',
  },

  // ─────────────── cap. 3 · Ingresso/uscita di base ───────────────
  {
    id: 'fig-3-1',
    diagramId: 'sistema-calcolo',
    code: 'fig. 3.1',
    desc: 'Un sistema di calcolo: processore, memoria e dispositivi sulla rete di interconnessione',
    area: 'cap. 3 · I/O di base',
    topic: 'io',
  },
  {
    id: 'fig-3-2',
    diagramId: 'interfaccia-io',
    code: 'fig. 3.2',
    desc: 'Connessione fra processore, tastiera e display: i registri DATA, STATUS e CONTROL',
    area: 'cap. 3 · I/O di base',
    topic: 'io',
  },
  {
    id: 'fig-3-6',
    code: 'fig. 3.6',
    desc: 'Trasferimento del controllo tramite interruzioni',
    area: 'cap. 3 · I/O di base',
    topic: 'irq',
  },
  {
    id: 'fig-3-7',
    diagramId: 'registri-controllo',
    code: 'fig. 3.7',
    desc: 'Registri di controllo del processore: PS, IPS, IENABLE, IPENDING',
    area: 'cap. 3 · I/O di base',
    topic: 'irq',
  },
  {
    id: 'fig-3-14',
    code: 'fig. 3.14',
    desc: 'Registri dell’interfaccia del timer',
    area: 'cap. 3 · I/O di base',
    topic: 'io',
  },
  {
    id: 'fig-3-16',
    code: 'fig. 3.16',
    desc: 'Programma in stile CISC (Esempio 3.5)',
    area: 'cap. 3 · I/O di base',
    topic: 'isa',
  },
  {
    id: 'fig-3-17',
    code: 'fig. 3.17',
    desc: 'Display a sette segmenti e relativa tabella di codifica',
    area: 'cap. 3 · I/O di base',
    topic: 'io',
  },

  // ─────────────── cap. 4 · Software ───────────────
  {
    id: 'fig-4-1',
    diagramId: 'catena-software',
    code: 'fig. 4.1',
    desc: 'Dal sorgente al programma oggetto: compilatore, assemblatore, collegatore',
    area: 'cap. 4 · Software',
    topic: 'sw',
  },
  {
    id: 'fig-4-7',
    code: 'fig. 4.7',
    desc: 'Diagramma temporale: il controllo passa fra programma utente e routine del sistema operativo',
    area: 'cap. 4 · Software',
    topic: 'sw',
  },

  // ─────────────── cap. 5 · Unità di elaborazione ───────────────
  {
    id: 'fig-5-1',
    diagramId: 'componenti-processore',
    code: 'fig. 5.1',
    desc: 'Componenti hardware principali di un processore',
    area: 'cap. 5 · Unità di elaborazione',
    topic: 'cpu',
  },
  {
    id: 'fig-5-2',
    code: 'fig. 5.2',
    desc: 'Struttura di base per l’elaborazione dei dati: registri, logica combinatoria, clock',
    area: 'cap. 5 · Unità di elaborazione',
    topic: 'cpu',
  },
  {
    id: 'fig-5-3',
    code: 'fig. 5.3',
    desc: 'Struttura hardware con più stadi separati da registri',
    area: 'cap. 5 · Unità di elaborazione',
    topic: 'pipe',
  },
  {
    id: 'fig-5-5',
    code: 'fig. 5.5',
    desc: 'Due alternative per realizzare un banco di registri a doppia porta',
    area: 'cap. 5 · Unità di elaborazione',
    topic: 'cpu',
  },
  {
    id: 'fig-5-6',
    code: 'fig. 5.6',
    desc: 'Vista concettuale dell’hardware necessario al calcolo',
    area: 'cap. 5 · Unità di elaborazione',
    topic: 'cpu',
  },
  {
    id: 'fig-5-7',
    diagramId: 'cinque-stadi',
    code: 'fig. 5.7',
    desc: 'Organizzazione a cinque stadi del processore',
    area: 'cap. 5 · Unità di elaborazione',
    topic: 'cpu',
  },
  {
    id: 'fig-5-8',
    diagramId: 'datapath',
    code: 'fig. 5.8',
    desc: 'Percorso dei dati (datapath) di un processore',
    area: 'cap. 5 · Unità di elaborazione',
    topic: 'cpu',
  },
  {
    id: 'fig-5-9',
    code: 'fig. 5.9',
    desc: 'Sezione di prelievo dell’istruzione',
    area: 'cap. 5 · Unità di elaborazione',
    topic: 'cpu',
  },
  {
    id: 'fig-5-10',
    code: 'fig. 5.10',
    desc: 'Generatore dell’indirizzo di istruzione',
    area: 'cap. 5 · Unità di elaborazione',
    topic: 'cpu',
  },
  {
    id: 'fig-5-11',
    code: 'fig. 5.11',
    desc: 'Sequenza di azioni per prelevare ed eseguire Add R3, R4, R5',
    area: 'cap. 5 · Unità di elaborazione',
    topic: 'cpu',
  },
  {
    id: 'fig-5-12',
    code: 'fig. 5.12',
    desc: 'Codifica delle istruzioni: formato a registri, con operando immediato, di chiamata',
    area: 'cap. 5 · Unità di elaborazione',
    topic: 'isa',
  },
  {
    id: 'fig-5-13',
    code: 'fig. 5.13',
    desc: 'Sequenza di azioni per Load R5, X(R7)',
    area: 'cap. 5 · Unità di elaborazione',
    topic: 'cpu',
  },
  {
    id: 'fig-5-14',
    code: 'fig. 5.14',
    desc: 'Sequenza di azioni per Store R6, X(R8)',
    area: 'cap. 5 · Unità di elaborazione',
    topic: 'cpu',
  },
  {
    id: 'fig-5-15',
    code: 'fig. 5.15',
    desc: 'Sequenza di azioni per un salto incondizionato',
    area: 'cap. 5 · Unità di elaborazione',
    topic: 'cpu',
  },
  {
    id: 'fig-5-18',
    code: 'fig. 5.18',
    desc: 'Segnali di controllo del percorso dei dati',
    area: 'cap. 5 · Unità di elaborazione',
    topic: 'cpu',
  },
  {
    id: 'fig-5-19',
    code: 'fig. 5.19',
    desc: 'Interfaccia processore-memoria e segnali di controllo dell’IR',
    area: 'cap. 5 · Unità di elaborazione',
    topic: 'cpu',
  },
  {
    id: 'fig-5-20',
    code: 'fig. 5.20',
    desc: 'Segnali di controllo del generatore di indirizzi',
    area: 'cap. 5 · Unità di elaborazione',
    topic: 'cpu',
  },
  {
    id: 'fig-5-21',
    diagramId: 'controllo-cablato',
    code: 'fig. 5.21',
    desc: 'Generazione dei segnali di controllo: decodificatore, contatore di passo, generatore',
    area: 'cap. 5 · Unità di elaborazione',
    topic: 'cpu',
  },
  {
    id: 'fig-5-22',
    code: 'fig. 5.22',
    desc: 'Organizzazione di un processore in stile CISC',
    area: 'cap. 5 · Unità di elaborazione',
    topic: 'cpu',
  },
  {
    id: 'fig-5-23',
    code: 'fig. 5.23',
    desc: 'Gating di ingresso e uscita per un bit di registro',
    area: 'cap. 5 · Unità di elaborazione',
    topic: 'ff',
  },
  {
    id: 'fig-5-24',
    diagramId: 'processore-3bus',
    code: 'fig. 5.24',
    desc: 'Processore CISC a tre bus',
    area: 'cap. 5 · Unità di elaborazione',
    topic: 'cpu',
  },
  {
    id: 'fig-5-27',
    diagramId: 'controllo-microprogrammato',
    code: 'fig. 5.27',
    desc: 'Organizzazione di un’unità di controllo microprogrammata',
    area: 'cap. 5 · Unità di elaborazione',
    topic: 'cpu',
  },
  {
    id: 'fig-5-28',
    code: 'fig. 5.28',
    desc: 'Connessione dei registri IPS e PS (Esempio 5.6)',
    area: 'cap. 5 · Unità di elaborazione',
    topic: 'irq',
  },

  // ─────────────── cap. 6 · Pipeline ───────────────
  {
    id: 'fig-6-1',
    code: 'fig. 6.1',
    desc: 'Esecuzione in pipeline: il caso ideale',
    area: 'cap. 6 · Pipeline',
    topic: 'pipe',
  },
  {
    id: 'fig-6-2',
    diagramId: 'pipeline-5-stadi',
    code: 'fig. 6.2',
    desc: 'Percorso dati a pipeline di cinque stadi, con i registri di stadio',
    area: 'cap. 6 · Pipeline',
    topic: 'pipe',
  },
  {
    id: 'fig-6-3',
    code: 'fig. 6.3',
    desc: 'Stallo della pipeline dovuto a dipendenza dai dati',
    area: 'cap. 6 · Pipeline',
    topic: 'pipe',
  },
  {
    id: 'fig-6-5',
    code: 'fig. 6.5',
    desc: 'Modifica del datapath per il forwarding da RZ agli ingressi della ALU',
    area: 'cap. 6 · Pipeline',
    topic: 'pipe',
  },
  {
    id: 'fig-6-6',
    code: 'fig. 6.6',
    desc: 'Uso di istruzioni NOP per gestire una dipendenza via software',
    area: 'cap. 6 · Pipeline',
    topic: 'pipe',
  },
  {
    id: 'fig-6-7',
    code: 'fig. 6.7',
    desc: 'Stallo causato dal ritardo di accesso alla memoria per una Load',
    area: 'cap. 6 · Pipeline',
    topic: 'pipe',
  },
  {
    id: 'fig-6-8',
    code: 'fig. 6.8',
    desc: 'Stallo necessario per abilitare il forwarding dopo una Load',
    area: 'cap. 6 · Pipeline',
    topic: 'pipe',
  },
  {
    id: 'fig-6-9',
    code: 'fig. 6.9',
    desc: 'Penalità di salto quando l’indirizzo è noto nello stadio di calcolo',
    area: 'cap. 6 · Pipeline',
    topic: 'pipe',
  },
  {
    id: 'fig-6-10',
    code: 'fig. 6.10',
    desc: 'Penalità di salto quando l’indirizzo è noto nello stadio di decodifica',
    area: 'cap. 6 · Pipeline',
    topic: 'pipe',
  },
  {
    id: 'fig-6-13',
    diagramId: 'superscalare',
    code: 'fig. 6.13',
    desc: 'Processore superscalare con due unità di esecuzione',
    area: 'cap. 6 · Pipeline',
    topic: 'pipe',
  },
  {
    id: 'fig-6-14',
    code: 'fig. 6.14',
    desc: 'Esempio di flusso di istruzioni nel processore superscalare',
    area: 'cap. 6 · Pipeline',
    topic: 'pipe',
  },
  {
    id: 'fig-6-15',
    code: 'fig. 6.15',
    desc: 'Esecuzione in pipeline delle istruzioni dell’Esempio 6.1',
    area: 'cap. 6 · Pipeline',
    topic: 'pipe',
  },

  // ─────────────── cap. 7 · Organizzazione dell’I/O ───────────────
  {
    id: 'fig-7-1',
    diagramId: 'bus-singolo',
    code: 'fig. 7.1',
    desc: 'Struttura a bus singolo',
    area: 'cap. 7 · Organizzazione dell’I/O',
    topic: 'io',
  },
  {
    id: 'fig-7-2',
    diagramId: 'interfaccia-ingresso',
    code: 'fig. 7.2',
    desc: 'Interfaccia di I/O per un dispositivo di ingresso',
    area: 'cap. 7 · Organizzazione dell’I/O',
    topic: 'io',
  },
  {
    id: 'fig-7-3',
    code: 'fig. 7.3',
    desc: 'Temporizzazione di un trasferimento in ingresso su bus sincrono',
    area: 'cap. 7 · Organizzazione dell’I/O',
    topic: 'io',
  },
  {
    id: 'fig-7-4',
    code: 'fig. 7.4',
    desc: 'Diagramma temporale dettagliato del trasferimento della fig. 7.3',
    area: 'cap. 7 · Organizzazione dell’I/O',
    topic: 'io',
  },
  {
    id: 'fig-7-5',
    code: 'fig. 7.5',
    desc: 'Trasferimento in ingresso che occupa più cicli di clock',
    area: 'cap. 7 · Organizzazione dell’I/O',
    topic: 'io',
  },
  {
    id: 'fig-7-6',
    code: 'fig. 7.6',
    desc: 'Handshake nel trasferimento durante un’operazione di ingresso',
    area: 'cap. 7 · Organizzazione dell’I/O',
    topic: 'io',
  },
  {
    id: 'fig-7-7',
    code: 'fig. 7.7',
    desc: 'Handshake nel trasferimento durante un’operazione di uscita',
    area: 'cap. 7 · Organizzazione dell’I/O',
    topic: 'io',
  },
  {
    id: 'fig-7-8',
    code: 'fig. 7.8',
    desc: 'Arbitraggio del bus fra più master',
    area: 'cap. 7 · Organizzazione dell’I/O',
    topic: 'io',
  },
  {
    id: 'fig-7-9',
    code: 'fig. 7.9',
    desc: 'Concessione del bus in base alle priorità',
    area: 'cap. 7 · Organizzazione dell’I/O',
    topic: 'io',
  },
  {
    id: 'fig-7-10',
    code: 'fig. 7.10',
    desc: 'Connessione della tastiera al processore',
    area: 'cap. 7 · Organizzazione dell’I/O',
    topic: 'io',
  },
  {
    id: 'fig-7-11',
    code: 'fig. 7.11',
    desc: 'Circuito di un’interfaccia di ingresso',
    area: 'cap. 7 · Organizzazione dell’I/O',
    topic: 'io',
  },
  {
    id: 'fig-7-12',
    code: 'fig. 7.12',
    desc: 'Circuito del blocco di stato dell’interfaccia di ingresso',
    area: 'cap. 7 · Organizzazione dell’I/O',
    topic: 'io',
  },
  {
    id: 'fig-7-13',
    code: 'fig. 7.13',
    desc: 'Connessione del display al processore',
    area: 'cap. 7 · Organizzazione dell’I/O',
    topic: 'io',
  },
  {
    id: 'fig-7-14',
    code: 'fig. 7.14',
    desc: 'Circuito di un’interfaccia di uscita',
    area: 'cap. 7 · Organizzazione dell’I/O',
    topic: 'io',
  },
  {
    id: 'fig-7-15',
    code: 'fig. 7.15',
    desc: 'Interfaccia seriale con registri a scorrimento',
    area: 'cap. 7 · Organizzazione dell’I/O',
    topic: 'io',
  },
  {
    id: 'fig-7-16',
    code: 'fig. 7.16',
    desc: 'Trasmissione seriale asincrona di un carattere: bit di start e di stop',
    area: 'cap. 7 · Organizzazione dell’I/O',
    topic: 'io',
  },
  {
    id: 'fig-7-17',
    diagramId: 'usb-albero',
    code: 'fig. 7.17',
    desc: 'Struttura ad albero dell’Universal Serial Bus',
    area: 'cap. 7 · Organizzazione dell’I/O',
    topic: 'io',
  },
  {
    id: 'fig-7-18',
    diagramId: 'pci-sistema',
    code: 'fig. 7.18',
    desc: 'Uso di un bus PCI in un sistema di calcolo',
    area: 'cap. 7 · Organizzazione dell’I/O',
    topic: 'io',
  },
  {
    id: 'fig-7-19',
    code: 'fig. 7.19',
    desc: 'Operazione di lettura sul bus PCI',
    area: 'cap. 7 · Organizzazione dell’I/O',
    topic: 'io',
  },
  {
    id: 'fig-7-20',
    code: 'fig. 7.20',
    desc: 'Connessioni PCI Express: root complex, switch, porte',
    area: 'cap. 7 · Organizzazione dell’I/O',
    topic: 'io',
  },
  {
    id: 'fig-7-21',
    code: 'fig. 7.21',
    desc: 'Diagramma degli stati per l’Esempio 7.2',
    area: 'cap. 7 · Organizzazione dell’I/O',
    topic: 'ff',
  },
  {
    id: 'fig-7-22',
    code: 'fig. 7.22',
    desc: 'Circuito di un’interfaccia di uscita sincrona (Esempio 7.3)',
    area: 'cap. 7 · Organizzazione dell’I/O',
    topic: 'io',
  },

  // ─────────────── cap. 8 · Il sistema di memoria ───────────────
  {
    id: 'fig-8-1',
    code: 'fig. 8.1',
    desc: 'Connessione della memoria al processore: linee indirizzi, dati e controllo',
    area: 'cap. 8 · Sistema di memoria',
    topic: 'mem',
  },
  {
    id: 'fig-8-2',
    diagramId: 'chip-memoria',
    code: 'fig. 8.2',
    desc: 'Organizzazione delle celle di bit in un chip di memoria',
    area: 'cap. 8 · Sistema di memoria',
    topic: 'mem',
  },
  {
    id: 'fig-8-3',
    code: 'fig. 8.3',
    desc: 'Organizzazione di un chip di memoria 1K × 1',
    area: 'cap. 8 · Sistema di memoria',
    topic: 'mem',
  },
  {
    id: 'fig-8-4',
    code: 'fig. 8.4',
    desc: 'Cella di RAM statica',
    area: 'cap. 8 · Sistema di memoria',
    topic: 'mem',
  },
  {
    id: 'fig-8-5',
    code: 'fig. 8.5',
    desc: 'Esempio di cella di memoria CMOS',
    area: 'cap. 8 · Sistema di memoria',
    topic: 'tech',
  },
  {
    id: 'fig-8-6',
    code: 'fig. 8.6',
    desc: 'Cella di memoria dinamica a un solo transistore',
    area: 'cap. 8 · Sistema di memoria',
    topic: 'mem',
  },
  {
    id: 'fig-8-7',
    code: 'fig. 8.7',
    desc: 'Organizzazione interna di un chip DRAM 32M × 8',
    area: 'cap. 8 · Sistema di memoria',
    topic: 'mem',
  },
  {
    id: 'fig-8-8',
    diagramId: 'dram-sincrona',
    code: 'fig. 8.8',
    desc: 'DRAM sincrona: latch di riga e colonna, contatore di refresh, registri dati',
    area: 'cap. 8 · Sistema di memoria',
    topic: 'mem',
  },
  {
    id: 'fig-8-10',
    code: 'fig. 8.10',
    desc: 'Modulo di memoria 2M × 32 costruito con chip statici 512K × 8',
    area: 'cap. 8 · Sistema di memoria',
    topic: 'mem',
  },
  {
    id: 'fig-8-13',
    diagramId: 'dma-sistema',
    code: 'fig. 8.13',
    desc: 'Uso dei controllori DMA in un sistema di calcolo',
    area: 'cap. 8 · Sistema di memoria',
    topic: 'io',
  },
  {
    id: 'fig-8-14',
    diagramId: 'gerarchia-memoria',
    code: 'fig. 8.14',
    desc: 'Gerarchia di memoria: registri, cache, memoria principale, disco',
    area: 'cap. 8 · Sistema di memoria',
    topic: 'mem',
  },
  {
    id: 'fig-8-15',
    code: 'fig. 8.15',
    desc: 'Uso di una memoria cache fra processore e memoria principale',
    area: 'cap. 8 · Sistema di memoria',
    topic: 'mem',
  },
  {
    id: 'fig-8-16',
    diagramId: 'cache-diretta',
    code: 'fig. 8.16',
    desc: 'Cache a mappatura diretta e scomposizione dell’indirizzo',
    area: 'cap. 8 · Sistema di memoria',
    topic: 'mem',
  },
  {
    id: 'fig-8-17',
    diagramId: 'cache-associativa',
    code: 'fig. 8.17',
    desc: 'Cache completamente associativa',
    area: 'cap. 8 · Sistema di memoria',
    topic: 'mem',
  },
  {
    id: 'fig-8-18',
    diagramId: 'cache-set-associativa',
    code: 'fig. 8.18',
    desc: 'Cache associativa a gruppi, con due blocchi per insieme',
    area: 'cap. 8 · Sistema di memoria',
    topic: 'mem',
  },
  {
    id: 'fig-8-24',
    diagramId: 'memoria-virtuale-org',
    code: 'fig. 8.24',
    desc: 'Organizzazione della memoria virtuale: MMU, cache, memoria, disco',
    area: 'cap. 8 · Sistema di memoria',
    topic: 'vm',
  },
  {
    id: 'fig-8-25',
    diagramId: 'memoria-virtuale-tlb',
    code: 'fig. 8.25',
    desc: 'Traduzione dell’indirizzo virtuale tramite la tabella delle pagine',
    area: 'cap. 8 · Sistema di memoria',
    topic: 'vm',
  },
  {
    id: 'fig-8-27',
    code: 'fig. 8.27',
    desc: 'Principi del disco magnetico: struttura meccanica, testina, codifica di fase',
    area: 'cap. 8 · Sistema di memoria',
    topic: 'mem',
  },
  {
    id: 'fig-8-29',
    code: 'fig. 8.29',
    desc: 'Disco ottico: sezione, transizione pit-land, motivo binario memorizzato',
    area: 'cap. 8 · Sistema di memoria',
    topic: 'mem',
  },
  {
    id: 'fig-8-30',
    code: 'fig. 8.30',
    desc: 'Organizzazione dei dati su nastro magnetico',
    area: 'cap. 8 · Sistema di memoria',
    topic: 'mem',
  },
  {
    id: 'fig-p8-1',
    code: 'fig. P8.1',
    desc: 'Struttura di un programma (Problema 8.5)',
    area: 'cap. 8 · Sistema di memoria',
    topic: 'mem',
  },
  {
    id: 'fig-p8-2',
    code: 'fig. P8.2',
    desc: 'Contenuto di cache e memoria principale (Problema 8.6)',
    area: 'cap. 8 · Sistema di memoria',
    topic: 'mem',
  },

  // ─────────────── cap. 9 · Aritmetica ───────────────
  {
    id: 'fig-9-1',
    code: 'fig. 9.1',
    desc: 'Specifica logica di uno stadio di addizione binaria',
    area: 'cap. 9 · Aritmetica',
    topic: 'arith',
  },
  {
    id: 'fig-9-2',
    diagramId: 'sommatore-ripple',
    code: 'fig. 9.2',
    desc: 'Logica per l’addizione binaria: sommatore completo e ripple-carry a n bit',
    area: 'cap. 9 · Aritmetica',
    topic: 'arith',
  },
  {
    id: 'fig-9-3',
    diagramId: 'sommatore-sottrattore',
    code: 'fig. 9.3',
    desc: 'Circuito di addizione/sottrazione binaria con controllo Add/Sub',
    area: 'cap. 9 · Aritmetica',
    topic: 'arith',
  },
  {
    id: 'fig-9-4',
    diagramId: 'carry-lookahead',
    code: 'fig. 9.4',
    desc: 'Sommatore a 4 bit con riporto anticipato: celle B e logica di lookahead',
    area: 'cap. 9 · Aritmetica',
    topic: 'arith',
  },
  {
    id: 'fig-9-5',
    code: 'fig. 9.5',
    desc: 'Sommatore a 16 bit costruito con quattro blocchi da 4 bit',
    area: 'cap. 9 · Aritmetica',
    topic: 'arith',
  },
  {
    id: 'fig-9-6',
    code: 'fig. 9.6',
    desc: 'Moltiplicazione ad array di operandi binari senza segno',
    area: 'cap. 9 · Aritmetica',
    topic: 'arith',
  },
  {
    id: 'fig-9-7',
    diagramId: 'moltiplicatore-sequenziale',
    code: 'fig. 9.7',
    desc: 'Moltiplicatore binario sequenziale: registri A, M, Q e sequenziatore',
    area: 'cap. 9 · Aritmetica',
    topic: 'arith',
  },
  {
    id: 'fig-9-16',
    code: 'fig. 9.16',
    desc: 'Array ripple-carry e carry-save per un moltiplicatore 4 × 4',
    area: 'cap. 9 · Aritmetica',
    topic: 'arith',
  },
  {
    id: 'fig-9-18',
    code: 'fig. 9.18',
    desc: 'Esempio di moltiplicazione svolto con addizione carry-save',
    area: 'cap. 9 · Aritmetica',
    topic: 'arith',
  },
  {
    id: 'fig-9-19',
    code: 'fig. 9.19',
    desc: 'Rappresentazione schematica delle addizioni carry-save',
    area: 'cap. 9 · Aritmetica',
    topic: 'arith',
  },
  {
    id: 'fig-9-23',
    diagramId: 'divisione-binaria',
    code: 'fig. 9.23',
    desc: 'Circuito per la divisione binaria: registri A, Q, M e sequenziatore',
    area: 'cap. 9 · Aritmetica',
    topic: 'arith',
  },
  {
    id: 'fig-9-25',
    code: 'fig. 9.25',
    desc: 'Esempio di divisione con il metodo non-restoring',
    area: 'cap. 9 · Aritmetica',
    topic: 'arith',
  },
  {
    id: 'fig-9-26',
    diagramId: 'ieee-formati',
    code: 'fig. 9.26',
    desc: 'Formati standard IEEE in virgola mobile: singola e doppia precisione',
    area: 'cap. 9 · Aritmetica',
    topic: 'ieee',
  },
  {
    id: 'fig-9-27',
    code: 'fig. 9.27',
    desc: 'Normalizzazione in virgola mobile, formato IEEE a singola precisione',
    area: 'cap. 9 · Aritmetica',
    topic: 'ieee',
  },
  {
    id: 'fig-9-28',
    diagramId: 'fp-somma',
    code: 'fig. 9.28',
    desc: 'Unità di addizione e sottrazione in virgola mobile',
    area: 'cap. 9 · Aritmetica',
    topic: 'ieee',
  },
  {
    id: 'fig-9-29',
    code: 'fig. 9.29',
    desc: 'Conversione da decimale a binario, parte intera e parte frazionaria',
    area: 'cap. 9 · Aritmetica',
    topic: 'bin',
  },
  {
    id: 'fig-p9-2',
    code: 'fig. P9.2',
    desc: 'Formato in virgola mobile a 12 bit (Problema 9.21)',
    area: 'cap. 9 · Aritmetica',
    topic: 'ieee',
  },

  // ─────────────── cap. 11 · Sistema su chip ───────────────
  {
    id: 'fig-11-1',
    code: 'fig. 11.1',
    desc: 'Registri dell’interfaccia parallela PIO',
    area: 'cap. 11 · Sistema su chip',
    topic: 'io',
  },
  {
    id: 'fig-11-2',
    code: 'fig. 11.2',
    desc: 'Registri dell’interfaccia del timer a intervalli',
    area: 'cap. 11 · Sistema su chip',
    topic: 'io',
  },
  {
    id: 'fig-11-4',
    diagramId: 'soc-sveglia',
    code: 'fig. 11.4',
    desc: 'Schema a blocchi della sveglia: processore, memoria, timer, periferiche',
    area: 'cap. 11 · Sistema su chip',
    topic: 'io',
  },
  {
    id: 'fig-11-5',
    code: 'fig. 11.5',
    desc: 'Sistema realizzato su FPGA con il SOPC Builder',
    area: 'cap. 11 · Sistema su chip',
    topic: 'tech',
  },

  // ─────────────── cap. 12 · Elaborazione parallela ───────────────
  {
    id: 'fig-12-2',
    diagramId: 'multiprocessore-uma',
    code: 'fig. 12.2',
    desc: 'Multiprocessore UMA: memorie condivise attraverso la rete di interconnessione',
    area: 'cap. 12 · Elaborazione parallela',
    topic: 'perf',
  },
  {
    id: 'fig-12-3',
    code: 'fig. 12.3',
    desc: 'Multiprocessore NUMA: ogni processore con la propria memoria locale',
    area: 'cap. 12 · Elaborazione parallela',
    topic: 'perf',
  },
  {
    id: 'fig-12-4',
    code: 'fig. 12.4',
    desc: 'Reti di interconnessione ad anello, singolo e gerarchico',
    area: 'cap. 12 · Elaborazione parallela',
    topic: 'perf',
  },
  {
    id: 'fig-12-5',
    code: 'fig. 12.5',
    desc: 'Rete di interconnessione a crossbar',
    area: 'cap. 12 · Elaborazione parallela',
    topic: 'perf',
  },

  // ─────────────── App. A · Circuiti logici ───────────────
  {
    id: 'fig-a-1',
    code: 'fig. A.1',
    desc: 'Esempio degli interruttori: connessione in parallelo (OR) e in serie (AND)',
    area: 'App. A · Circuiti logici',
    topic: 'bool',
  },
  {
    id: 'fig-a-2',
    code: 'fig. A.2',
    desc: 'Simboli standard delle porte logiche: OR, AND, NOT, XOR',
    area: 'App. A · Circuiti logici',
    topic: 'bool',
  },
  {
    id: 'fig-a-3',
    code: 'fig. A.3',
    desc: 'Realizzazione della funzione XOR con AND, OR e NOT',
    area: 'App. A · Circuiti logici',
    topic: 'bool',
  },
  {
    id: 'fig-a-4',
    code: 'fig. A.4',
    desc: 'Una rete logica e la rete minima equivalente',
    area: 'App. A · Circuiti logici',
    topic: 'karnaugh',
  },
  {
    id: 'fig-a-7',
    code: 'fig. A.7',
    desc: 'Porte NAND e NOR con le rispettive tabelle di verità',
    area: 'App. A · Circuiti logici',
    topic: 'bool',
  },
  {
    id: 'fig-a-8',
    code: 'fig. A.8',
    desc: 'Equivalenza fra rete NAND-NAND e rete AND-OR',
    area: 'App. A · Circuiti logici',
    topic: 'bool',
  },
  {
    id: 'fig-a-9',
    code: 'fig. A.9',
    desc: 'Porte in cascata: funzioni a tre ingressi con porte a due ingressi',
    area: 'App. A · Circuiti logici',
    topic: 'tech',
  },
  {
    id: 'fig-a-10',
    code: 'fig. A.10',
    desc: 'Rappresentazione dei valori logici mediante livelli di tensione',
    area: 'App. A · Circuiti logici',
    topic: 'tech',
  },
  {
    id: 'fig-a-11',
    code: 'fig. A.11',
    desc: 'Circuito invertitore: interruttore e transistore',
    area: 'App. A · Circuiti logici',
    topic: 'tech',
  },
  {
    id: 'fig-a-12',
    code: 'fig. A.12',
    desc: 'Realizzazione a transistori di una porta NOR',
    area: 'App. A · Circuiti logici',
    topic: 'tech',
  },
  {
    id: 'fig-a-13',
    code: 'fig. A.13',
    desc: 'Realizzazione a transistori di una porta NAND',
    area: 'App. A · Circuiti logici',
    topic: 'tech',
  },
  {
    id: 'fig-a-14',
    code: 'fig. A.14',
    desc: 'Transistori NMOS e PMOS nei circuiti logici',
    area: 'App. A · Circuiti logici',
    topic: 'tech',
  },
  {
    id: 'fig-a-15',
    code: 'fig. A.15',
    desc: 'Realizzazione CMOS della porta NOT',
    area: 'App. A · Circuiti logici',
    topic: 'tech',
  },
  {
    id: 'fig-a-16',
    diagramId: 'cmos-struttura',
    code: 'fig. A.16',
    desc: 'Struttura di un circuito CMOS: rete di pull-up e rete di pull-down',
    area: 'App. A · Circuiti logici',
    topic: 'tech',
  },
  {
    id: 'fig-a-17',
    code: 'fig. A.17',
    desc: 'Realizzazione CMOS della porta NAND',
    area: 'App. A · Circuiti logici',
    topic: 'tech',
  },
  {
    id: 'fig-a-18',
    code: 'fig. A.18',
    desc: 'Realizzazione CMOS della porta NOR',
    area: 'App. A · Circuiti logici',
    topic: 'tech',
  },
  {
    id: 'fig-a-19',
    code: 'fig. A.19',
    desc: 'Realizzazione CMOS della porta AND',
    area: 'App. A · Circuiti logici',
    topic: 'tech',
  },
  {
    id: 'fig-a-20',
    code: 'fig. A.20',
    desc: 'Caratteristica di trasferimento dell’invertitore CMOS',
    area: 'App. A · Circuiti logici',
    topic: 'tech',
  },
  {
    id: 'fig-a-21',
    code: 'fig. A.21',
    desc: 'Definizione di ritardo di propagazione e tempo di transizione',
    area: 'App. A · Circuiti logici',
    topic: 'tech',
  },
  {
    id: 'fig-a-22',
    code: 'fig. A.22',
    desc: 'Buffer tri-state: simbolo, circuito equivalente, tabella di verità',
    area: 'App. A · Circuiti logici',
    topic: 'comb',
  },
  {
    id: 'fig-a-23',
    code: 'fig. A.23',
    desc: 'Latch di base realizzato con porte NOR',
    area: 'App. A · Circuiti logici',
    topic: 'ff',
  },
  {
    id: 'fig-a-24',
    code: 'fig. A.24',
    desc: 'Latch SR con abilitazione (gated SR latch)',
    area: 'App. A · Circuiti logici',
    topic: 'ff',
  },
  {
    id: 'fig-a-25',
    code: 'fig. A.25',
    desc: 'Latch SR con abilitazione realizzato con porte NAND',
    area: 'App. A · Circuiti logici',
    topic: 'ff',
  },
  {
    id: 'fig-a-26',
    code: 'fig. A.26',
    desc: 'Latch D con abilitazione, tabella di verità e cronogramma',
    area: 'App. A · Circuiti logici',
    topic: 'ff',
  },
  {
    id: 'fig-a-27',
    diagramId: 'master-slave',
    code: 'fig. A.27',
    desc: 'Flip-flop D master-slave',
    area: 'App. A · Circuiti logici',
    topic: 'ff',
  },
  {
    id: 'fig-a-28',
    code: 'fig. A.28',
    desc: 'Flip-flop D sensibile al fronte di discesa, con setup e hold',
    area: 'App. A · Circuiti logici',
    topic: 'ff',
  },
  {
    id: 'fig-a-29',
    code: 'fig. A.29',
    desc: 'Flip-flop T: circuito, tabella di verità e cronogramma',
    area: 'App. A · Circuiti logici',
    topic: 'ff',
  },
  {
    id: 'fig-a-30',
    code: 'fig. A.30',
    desc: 'Flip-flop JK: circuito, tabella di verità e simbolo',
    area: 'App. A · Circuiti logici',
    topic: 'ff',
  },
  {
    id: 'fig-a-31',
    code: 'fig. A.31',
    desc: 'Flip-flop D master-slave con Preset e Clear',
    area: 'App. A · Circuiti logici',
    topic: 'ff',
  },
  {
    id: 'fig-a-32',
    diagramId: 'registro-scorrimento',
    code: 'fig. A.32',
    desc: 'Registro a scorrimento semplice',
    area: 'App. A · Circuiti logici',
    topic: 'ff',
  },
  {
    id: 'fig-a-33',
    code: 'fig. A.33',
    desc: 'Registro a scorrimento ad accesso parallelo',
    area: 'App. A · Circuiti logici',
    topic: 'ff',
  },
  {
    id: 'fig-a-34',
    diagramId: 'contatore-3bit',
    code: 'fig. A.34',
    desc: 'Contatore binario a 3 bit con flip-flop T',
    area: 'App. A · Circuiti logici',
    topic: 'ff',
  },
  {
    id: 'fig-a-35',
    diagramId: 'decoder-2-4',
    code: 'fig. A.35',
    desc: 'Decodificatore a due ingressi e quattro uscite',
    area: 'App. A · Circuiti logici',
    topic: 'comb',
  },
  {
    id: 'fig-a-36',
    code: 'fig. A.36',
    desc: 'Decodificatore da BCD a display a sette segmenti',
    area: 'App. A · Circuiti logici',
    topic: 'comb',
  },
  {
    id: 'fig-a-37',
    diagramId: 'mux-4-1',
    code: 'fig. A.37',
    desc: 'Multiplexer a quattro ingressi',
    area: 'App. A · Circuiti logici',
    topic: 'comb',
  },
  {
    id: 'fig-a-38',
    code: 'fig. A.38',
    desc: 'Realizzazione di una funzione logica con un multiplexer',
    area: 'App. A · Circuiti logici',
    topic: 'comb',
  },
  {
    id: 'fig-a-39',
    diagramId: 'pld-blocchi',
    code: 'fig. A.39',
    desc: 'Schema a blocchi di un dispositivo logico programmabile (PLD)',
    area: 'App. A · Circuiti logici',
    topic: 'tech',
  },
  {
    id: 'fig-a-44',
    code: 'fig. A.44',
    desc: 'Organizzazione di un dispositivo logico programmabile complesso (CPLD)',
    area: 'App. A · Circuiti logici',
    topic: 'tech',
  },
  {
    id: 'fig-a-45',
    diagramId: 'fpga',
    code: 'fig. A.45',
    desc: 'Schema concettuale di una FPGA: blocchi logici, interconnessioni, blocchi di I/O',
    area: 'App. A · Circuiti logici',
    topic: 'tech',
  },
  {
    id: 'fig-a-49',
    code: 'fig. A.49',
    desc: 'Realizzazione del contatore su/giù',
    area: 'App. A · Circuiti logici',
    topic: 'ff',
  },
  {
    id: 'fig-a-51',
    diagramId: 'macchina-stati',
    code: 'fig. A.51',
    desc: 'Modello formale di una macchina a stati finiti',
    area: 'App. A · Circuiti logici',
    topic: 'ff',
  },
];

/** Le aree del catalogo, nell'ordine del testo. */
export const FIGURE_AREAS: string[] = [...new Set(figures.map((figure) => figure.area))];
