import type { McqItem } from './types';

/**
 * Banca delle crocette (49 voci), raggruppate per argomento.
 *
 * PER AGGIUNGERE UNA DOMANDA: copia una voce nella sezione giusta, dàlle un
 * `id` non usato, scrivi le 4 alternative in `options` e metti in `correct`
 * l'indice (0-based) di quella esatta. Il motore rimescola le alternative a
 * ogni generazione, quindi l'ordine che scrivi qui non conta.
 *
 * `q` e `options` accettano markup inline (<b>, <code>).
 */
export const mcq: McqItem[] = [
  // ══════════════════ Algebra di Boole & porte ══════════════════
  {
    id: 'mcq-bool-01',
    topic: 'bool',
    q: "Quali operatori rendono l'algebra di Boole funzionalmente completa da soli?",
    options: ['AND e OR', 'NAND e NOR', 'NOT e AND', 'XOR e OR'],
    correct: 1,
    ref: 'Hamacher App. A',
  },
  {
    id: 'mcq-bool-02',
    topic: 'bool',
    q: 'Con soli AND e OR, perché non si sintetizza ogni funzione?',
    options: ['Manca la negazione', 'Sono troppo lenti', 'Non sono associativi', 'Consumano troppo'],
    correct: 0,
    ref: 'Hamacher App. A',
  },
  {
    id: 'mcq-bool-03',
    topic: 'bool',
    q: 'Quale porta logica si ottiene combinando due NAND?',
    options: ['OR', 'AND', 'NOR', 'XNOR'],
    correct: 1,
    ref: 'Hamacher App. A',
  },

  // ══════════════════ Numeri binari & complemento a 2 ══════════════════
  {
    id: 'mcq-bin-01',
    topic: 'bin',
    q: 'La base del sistema numerico Maya è:',
    options: ['10 (decimale)', '20 (vigesimale)', '16 (esadecimale)', '8 (ottale)'],
    correct: 1,
    ref: 'Hamacher cap. 1',
  },
  {
    id: 'mcq-bin-02',
    topic: 'bin',
    q: 'Uno shift a sinistra di un intero equivale a:',
    options: ['Divisione per 2', 'Moltiplicazione per 2', 'Negazione', 'Complemento a 1'],
    correct: 1,
    ref: 'Hamacher cap. 1',
  },
  {
    id: 'mcq-bin-03',
    topic: 'bin',
    q: 'Quali rappresentazioni hanno due codifiche dello zero?',
    options: ['CP2', 'Senza segno', 'Complemento a 1 e modulo-e-segno', 'Esadecimale'],
    correct: 2,
    ref: 'Hamacher cap. 1',
  },
  {
    id: 'mcq-bin-04',
    topic: 'bin',
    q: 'Eliminare il bit meno significativo di un intero senza segno equivale a:',
    options: ['Moltiplicare per 2', 'Dividere (intero) per 2', 'Negare', 'Nulla'],
    correct: 1,
    ref: 'Hamacher cap. 1',
  },
  {
    id: 'mcq-bin-05',
    topic: 'bin',
    q: 'In una rappresentazione Big Endian, il bit di segno si trova:',
    options: [
      'Alla fine',
      "All'inizio (byte più significativo)",
      'Al centro',
      'In un registro a parte',
    ],
    correct: 1,
    ref: 'Hamacher cap. 2',
  },
  {
    id: 'mcq-bin-06',
    topic: 'bin',
    q: 'Quante cifre esadecimali servono per rappresentare 33?',
    options: ['1', '2', '3', '4'],
    correct: 1,
    ref: 'Hamacher cap. 1',
  },
  {
    id: 'mcq-bin-07',
    topic: 'bin',
    q: "Quale porta rileva l'overflow sommando due numeri con n bit?",
    options: ['AND', 'OR', 'XOR', 'NAND'],
    correct: 2,
    ref: 'Hamacher cap. 1',
  },
  {
    id: 'mcq-bin-08',
    topic: 'bin',
    q: 'Come ti accorgi di un overflow sommando due positivi in CP2?',
    options: [
      'Ottieni un numero negativo',
      'Ottieni zero',
      'Il risultato raddoppia',
      'Nessun segnale',
    ],
    correct: 0,
    ref: 'Hamacher cap. 1',
  },
  {
    id: 'mcq-bin-09',
    topic: 'bin',
    q: "In CP2 l'overflow può verificarsi nella:",
    options: [
      'Somma di due discordi',
      'Sottrazione di due discordi',
      'Somma con lo zero',
      'Divisione',
    ],
    correct: 1,
    ref: 'Hamacher cap. 1',
  },

  // ══════════════════ Circuiti sequenziali ══════════════════
  {
    id: 'mcq-ff-01',
    topic: 'ff',
    q: "Che cos'è un flip-flop?",
    options: [
      'Un registro a 8 bit',
      'Un elemento bistabile che memorizza 1 bit',
      'Una porta logica universale',
      'Un tipo di bus',
    ],
    correct: 1,
    ref: 'Hamacher App. A',
  },
  {
    id: 'mcq-ff-02',
    topic: 'ff',
    q: 'Un flip-flop master-slave è di tipo:',
    options: ['Asincrono', 'Sincrono (edge-triggered)', 'Combinatorio', 'Analogico'],
    correct: 1,
    ref: 'Hamacher App. A',
  },

  // ══════════════════ RISC/CISC & assembly ══════════════════
  {
    id: 'mcq-isa-01',
    topic: 'isa',
    q: 'RISC sta per:',
    options: [
      'Reduced Instruction Set Computing',
      'Rapid Internal Signal Control',
      'Random Instruction Sequence Computing',
      'Reduced Internal Storage Cache',
    ],
    correct: 0,
    ref: 'Hamacher cap. 2',
  },
  {
    id: 'mcq-isa-02',
    topic: 'isa',
    q: "Caratteristica tipica di un'architettura RISC:",
    options: [
      'Istruzioni di lunghezza variabile',
      'Operazioni memoria-memoria',
      'Modello load/store con istruzioni a lunghezza fissa',
      'Nessuna pipeline',
    ],
    correct: 2,
    ref: 'Hamacher cap. 2',
  },
  {
    id: 'mcq-isa-03',
    topic: 'isa',
    q: 'In <code>Add R1,R2,R3</code>, dove finisce il risultato?',
    options: ['In R2', 'In R3', 'In R1', 'In memoria LOC'],
    correct: 2,
    ref: 'Hamacher cap. 2',
  },
  {
    id: 'mcq-isa-04',
    topic: 'isa',
    q: 'Il loader si occupa principalmente di:',
    options: [
      'Compilare il codice',
      'Caricare programmi in memoria (e dello spiazzamento)',
      'Gestire gli interrupt',
      'Sostituire i blocchi cache',
    ],
    correct: 1,
    ref: 'Hamacher cap. 2',
  },
  {
    id: 'mcq-isa-05',
    topic: 'isa',
    q: 'Il linker serve a:',
    options: [
      'Tradurre in linguaggio macchina',
      'Combinare più file oggetto risolvendo i riferimenti esterni',
      'Gestire la memoria virtuale',
      'Cancellare la EPROM',
    ],
    correct: 1,
    ref: 'Hamacher cap. 2',
  },
  {
    id: 'mcq-isa-06',
    topic: 'isa',
    q: 'Chi traduce il codice sorgente in linguaggio macchina?',
    options: ['Il sistema operativo', 'Il compilatore', 'Il loader', 'La ALU'],
    correct: 1,
    ref: 'Hamacher cap. 2',
  },
  {
    id: 'mcq-isa-07',
    topic: 'isa',
    q: 'Quale istruzione ARM trasferisce un valore da un registro a un altro?',
    options: ['CMP', 'ADD', 'SUB', 'MOV'],
    correct: 3,
    ref: 'Hamacher cap. 3',
  },
  {
    id: 'mcq-isa-08',
    topic: 'isa',
    q: 'Quale istruzione realizza un salto condizionato «se maggiore»?',
    options: ['BGT', 'MOV', 'MUL', 'CLR'],
    correct: 0,
    ref: 'Hamacher cap. 2',
  },

  // ══════════════════ Interruzioni, eccezioni, I/O ══════════════════
  {
    id: 'mcq-irq-01',
    topic: 'irq',
    q: 'Le interruzioni hardware sono eventi:',
    options: ['Sincroni', 'Asincroni', 'Deterministici sul clock', 'Generati dalla ALU'],
    correct: 1,
    ref: 'Hamacher cap. 4',
  },
  {
    id: 'mcq-irq-02',
    topic: 'irq',
    q: 'Le eccezioni sono generate:',
    options: [
      'Da dispositivi esterni',
      "Dal processore durante l'esecuzione",
      'Solo dalla tastiera',
      'Dal bus dati',
    ],
    correct: 1,
    ref: 'Hamacher cap. 4',
  },
  {
    id: 'mcq-irq-03',
    topic: 'irq',
    q: 'Le richieste di interruzione viaggiano su quali linee del bus?',
    options: ['Linee dati', 'Linee indirizzi', 'Linee di controllo', 'Linee di alimentazione'],
    correct: 2,
    ref: 'Hamacher cap. 4',
  },
  {
    id: 'mcq-irq-04',
    topic: 'irq',
    q: "La <b>trace mode</b> del debugger genera un'interruzione:",
    options: ['A ogni breakpoint', 'Dopo ogni istruzione', 'A fine programma', 'Mai'],
    correct: 1,
    ref: 'Hamacher cap. 4',
  },
  {
    id: 'mcq-irq-05',
    topic: 'irq',
    q: 'Chi gestisce la scrittura sulla memoria di massa?',
    options: ['La cache', 'Il sistema operativo', 'Il compilatore', 'Il registro PC'],
    correct: 1,
    ref: 'Hamacher cap. 4',
  },
  {
    id: 'mcq-irq-06',
    topic: 'irq',
    q: 'Quale meccanismo compensa la differenza di velocità tra due dispositivi?',
    options: ['Il buffer', 'La ALU', 'Il PC', 'Il flip-flop'],
    correct: 0,
    ref: 'Hamacher cap. 4',
  },
  {
    id: 'mcq-irq-07',
    topic: 'irq',
    q: "Un'eccezione è sollevata se un processo tenta di…",
    options: [
      'Modificare la priorità di altri processi',
      'Accedere alla memoria di altri utenti',
      'Modificare la modalità del sistema',
      'Tutte le precedenti',
    ],
    correct: 3,
    ref: 'Hamacher cap. 4',
  },
  {
    id: 'mcq-irq-08',
    topic: 'irq',
    q: 'Gli interrupt sono particolarmente importanti nei sistemi:',
    options: ['Batch', 'Real-time', 'A singolo task', 'Analogici'],
    correct: 1,
    ref: 'Hamacher cap. 4',
  },
  {
    id: 'mcq-irq-09',
    topic: 'irq',
    q: 'Le interruzioni sono fondamentali per i sistemi:',
    options: ['Monotasking', 'Multitasking', 'Combinatori', 'Puramente sincroni'],
    correct: 1,
    ref: 'Hamacher cap. 4',
  },
  {
    id: 'mcq-irq-10',
    topic: 'irq',
    q: 'Cosa viene trasportato da un bus?',
    options: [
      'Solo dati',
      'Solo indirizzi',
      'Dati, indirizzi e segnali di controllo',
      'Solo controlli',
    ],
    correct: 2,
    ref: 'Hamacher cap. 4',
  },
  {
    id: 'mcq-irq-11',
    topic: 'irq',
    q: 'Come vengono trasmessi i dati su USB?',
    options: ['In parallelo', 'In modo seriale', 'Solo in analogico', 'Sul bus indirizzi'],
    correct: 1,
    ref: 'Hamacher cap. 4',
  },

  // ══════════════════ Processore, pipeline, prestazioni ══════════════════
  {
    id: 'mcq-pipe-01',
    topic: 'pipe',
    q: 'Il miglioramento del pipelining deriva da:',
    options: [
      'Clock più veloce',
      'Sovrapposizione (parallelismo) delle fasi delle istruzioni',
      'Meno registri',
      'Cache più grande',
    ],
    correct: 1,
    ref: 'Hamacher cap. 6',
  },
  {
    id: 'mcq-pipe-02',
    topic: 'pipe',
    q: 'La dipendenza dai dati in pipeline si mitiga con:',
    options: [
      'Operand forwarding',
      'Aumento del clock',
      'Riduzione dei registri',
      'Disattivare la cache',
    ],
    correct: 0,
    ref: 'Hamacher cap. 6',
  },
  {
    id: 'mcq-pipe-03',
    topic: 'pipe',
    q: 'Le prestazioni del processore dipendono dalla velocità di:',
    options: [
      'Solo esecuzione',
      'Prelievo (fetch) ed esecuzione',
      'Solo decodifica',
      'Solo scrittura',
    ],
    correct: 1,
    ref: 'Hamacher cap. 5',
  },
  {
    id: 'mcq-pipe-04',
    topic: 'pipe',
    q: 'Dove salva la ALU i risultati intermedi di un calcolo?',
    options: ['In cache', 'Nei registri', 'In memoria secondaria', 'Nel PC'],
    correct: 1,
    ref: 'Hamacher cap. 5',
  },

  // ══════════════════ Memoria & cache ══════════════════
  {
    id: 'mcq-mem-01',
    topic: 'mem',
    q: "Che cos'è un cache <b>miss</b>?",
    options: [
      'Il dato è in cache',
      'Il dato non è in cache e si scende nella gerarchia',
      'La cache è piena',
      'Un errore di parità',
    ],
    correct: 1,
    ref: 'Hamacher cap. 8',
  },
  {
    id: 'mcq-mem-02',
    topic: 'mem',
    q: 'Il ritardo introdotto dopo un cache miss si chiama:',
    options: ['hit ratio', 'miss penalty', 'write-back', 'latch delay'],
    correct: 1,
    ref: 'Hamacher cap. 8',
  },
  {
    id: 'mcq-mem-03',
    topic: 'mem',
    q: 'Quali proprietà sfrutta la cache?',
    options: [
      'Solo temporale',
      'Solo spaziale',
      'Località spaziale e temporale',
      'Nessuna delle due',
    ],
    correct: 2,
    ref: 'Hamacher cap. 8',
  },
  {
    id: 'mcq-mem-04',
    topic: 'mem',
    q: 'Algoritmo di sostituzione più comune in cache:',
    options: ['FIFO', 'LRU', 'Random', 'MRU'],
    correct: 1,
    ref: 'Hamacher cap. 8',
  },
  {
    id: 'mcq-mem-05',
    topic: 'mem',
    q: 'La EPROM si cancella:',
    options: [
      'Elettricamente',
      'Con raggi ultravioletti',
      'Meccanicamente',
      'Non si cancella',
    ],
    correct: 1,
    ref: 'Hamacher cap. 8',
  },
  {
    id: 'mcq-mem-06',
    topic: 'mem',
    q: 'La EEPROM si cancella:',
    options: ['Con raggi UV', 'Elettricamente', 'Termicamente', 'Con luce visibile'],
    correct: 1,
    ref: 'Hamacher cap. 8',
  },
  {
    id: 'mcq-mem-07',
    topic: 'mem',
    q: 'La memoria cache è tipicamente realizzata con:',
    options: ['DRAM', 'SRAM', 'EEPROM', 'Disco'],
    correct: 1,
    ref: 'Hamacher cap. 8',
  },
  {
    id: 'mcq-mem-08',
    topic: 'mem',
    q: 'Quale memoria è la più lenta della gerarchia?',
    options: ['Cache L1', 'Registri', 'Memoria secondaria', 'SRAM'],
    correct: 2,
    ref: 'Hamacher cap. 8',
  },
  {
    id: 'mcq-mem-09',
    topic: 'mem',
    q: 'Principale svantaggio di una DRAM molto grande:',
    options: [
      'Consuma poco',
      'Ne viene compromessa la velocità',
      'È troppo veloce',
      'Non serve refresh',
    ],
    correct: 1,
    ref: 'Hamacher cap. 8',
  },
  {
    id: 'mcq-mem-10',
    topic: 'mem',
    q: 'Perché una cella DRAM va rinfrescata periodicamente?',
    options: [
      'Il transistor si rompe',
      'Il condensatore si scarica per correnti di dispersione',
      'Il clock si ferma',
      'La cache la sovrascrive',
    ],
    correct: 1,
    ref: 'Hamacher cap. 8',
  },
  {
    id: 'mcq-mem-11',
    topic: 'mem',
    q: 'La SRAM (celle della cache) rispetto alla DRAM:',
    options: [
      'Necessita di refresh',
      'Non necessita di refresh',
      'È più lenta',
      'È più densa',
    ],
    correct: 1,
    ref: 'Hamacher cap. 8',
  },

  // ══════════════════ Virgola mobile ══════════════════
  {
    id: 'mcq-ieee-01',
    topic: 'ieee',
    q: 'Lo standard per la rappresentazione in virgola mobile è:',
    options: ['ASCII', 'IEEE 754', 'Unicode', 'ISO 8859'],
    correct: 1,
    ref: 'Hamacher cap. 1',
  },
];
